In [1]:
import gym
import numpy as np
import torch

from stable_baselines3 import SAC, PPO, HerReplayBuffer
from stable_baselines3.common.buffers import DictReplayBuffer
from stable_baselines3.sac.policies import MlpPolicy
from stable_baselines3.common.vec_env import DummyVecEnv, SubprocVecEnv, VecNormalize
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.utils import set_random_seed
from stable_baselines3.common.monitor import Monitor

from stable_baselines3.common import results_plotter
from stable_baselines3.common.results_plotter import load_results, ts2xy, plot_results
from stable_baselines3.common.noise import NormalActionNoise
from stable_baselines3.common.callbacks import BaseCallback

import numpy as np
import gym

from Lorenz96_Env_ICs import Lorenz96Env
from stable_baselines3 import PPO
import time 
import matplotlib.pyplot as plt
from typing import Callable

import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"   # see issue #152
os.environ["CUDA_VISIBLE_DEVICES"]="0"

from stable_baselines3.common.evaluation import evaluate_policy

In [2]:
def make_env(env_id, rank, integ_step, noise, seed=0):
    """
    Utility function for multiprocessed env.

    :param env_id: (str) the environment ID
    :param num_env: (int) the number of environments you wish to have in subprocesses
    :param seed: (int) the inital seed for RNG
    :param rank: (int) index of the subprocess
    """
    def _init():
        env = Lorenz96Env(integ_steps = integ_step)
        env.seed(seed + rank)
        return env
    set_random_seed(seed+ rank)
    return _init

In [3]:
num_cpu = 70  # Number of processes to use
# Create the vectorized environment
env = SubprocVecEnv([make_env('Lorenz', rank=i, integ_step=int(16), noise=1.0) for i in range(num_cpu)])
env = VecNormalize(env, norm_obs=True, norm_reward=False)

torch.backends.cudnn.benchmark = True

neuron = 128
lr = 0.001
gamma = 0.1
tSteps = 5000000
bs = 100
max_grad_norms = 0.8
vf = 0.9


/home/hammoumr/anaconda3/envs/sb3_v2/lib/python3.8/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(
/home/hammoumr/anaconda3/envs/sb3_v2/lib/python3.8/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(
/home/hammoumr/anaconda3/envs/sb3_v2/lib/python3.8/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(
/home/hammoumr/anaconda3/envs/sb3_v2/lib/python3.8/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(
/home/hammoumr/anaconda3/envs/sb3_v2/lib/python3.8/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(
/home/hammoumr/anaconda3/envs/sb3_v2/lib/python3.8/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting 

In [9]:
# model = PPO.load('trainedModels_L96_assimSteps4_obsNosie1.0_ICs_v2/'+'neurons'+str(neuron)+'_LR'+str(lr)+'_Gamma'+str(gamma)+'_BS'+str(bs)+'_totSteps5000000_assimStep4_obsNosie1.0_maxgradnorm'+str(max_grad_norms)+'_vfcoeff'+str(vf)+'/'+'PPO_Lorenz96', env=env)
model = PPO.load('trainedModels_L96_assimSteps4_obsNosie1.0_Markov1Step_TrueNorm/'+'neurons'+str(neuron)+'_LR'+str(lr)+'_Gamma'+str(gamma)+'_BS'+str(bs)+'_totSteps2500000_assimStep4_obsNosie1.0_maxgradnorm'+str(max_grad_norms)+'_vfcoeff'+str(vf)+'/'+'PPO_Lorenz96', env=env)
obs = env.reset()

solution = []
ref_soln = []
rewards_ = []

for _ in range(int(5000)):
    # action, _states = model.predict(obs, deterministic=True)
    action, _states = model.predict(obs, deterministic=False)
    obs, rewards, dones, info = env.step(action)
    trueObs = env.get_original_obs()
    trueRew = env.get_original_reward()
    trueRef = env.env_method("_get_ref", 1)

    solution.append(trueObs)
    ref_soln.append(trueRef)
    rewards_.append(trueRew)

sol2 = np.asarray(solution)
solR = np.asarray(ref_soln)


In [10]:

counter = 0
x = np.zeros((int(5000), 70, 40))
xR = np.zeros((int(5000), 70, 40))
RMSE  = np.zeros((int(5000), 70))
RRMSE = np.zeros((int(5000), 70))

x  = sol2[:, :, -40:]
xR = solR[:, :, -40:]

RMSE  = 0.85*np.sqrt(np.mean((x-xR)**2, axis=-1))
RRMSE = RMSE / np.sqrt(np.mean((xR)**2, axis=-1))

print(RRMSE)

[[0.74568405 0.65525098 0.7092883  ... 0.63594066 0.64378041 0.68935059]
 [1.11088758 1.00931081 1.03956205 ... 1.09380414 1.18763762 1.00070253]
 [1.2067625  1.25654814 1.16061601 ... 1.25964188 1.21356667 1.16395128]
 ...
 [0.90349129 0.9222238  0.91223809 ... 1.13836681 0.98805225 0.86195473]
 [0.89946007 0.92519884 0.96340338 ... 1.09322555 0.80148004 0.871584  ]
 [1.03513277 0.95967157 0.8470247  ... 1.05094144 0.77652433 0.86045048]]


In [11]:

# plt.clf()
# plt.figure(figsize=(12, 6))
# fig1 = plt.gcf()

# plt.subplot(1, 3, 2)
# plt.plot(t1, x)  # Plot some data on the axes.
# # plt.xlim((0, 1700))
# plt.subplot(1, 3, 1)
# plt.plot(t1, xR)  # Plot some data on the axes.
# # plt.xlim((0, 1700))
# plt.subplot(1, 3, 3)
# plt.plot(t1, x-xR)  # Plot some data on the axes.
# plt.show()


In [12]:

# plt.clf()
# plt.figure(figsize=(12, 6))
# fig1 = plt.gcf()

# plt.subplot(1, 3, 2)
# plt.plot(t1, y)  # Plot some data on the axes.
# # plt.xlim((0, 1700))
# plt.subplot(1, 3, 1)
# plt.plot(t1, yR)  # Plot some data on the axes.
# # plt.xlim((0, 1700))
# plt.subplot(1, 3, 3)
# plt.plot(t1, y-yR)  # Plot some data on the axes.
# plt.show()


In [13]:
model.save('data_ev16/'+'neurons'+str(neuron)+'_LR'+str(lr)+'_Gamma'+str(gamma)+'_BS'+str(bs)+'_totSteps'+str(tSteps)+'_assimStep50_obsNosie1.0_maxgradnorm'+str(max_grad_norms)+'_vfcoeff'+str(vf)+'/PPO_Gaussian_lossDifference_L96_fullObs_GaussianNoise_every50')

np.savez('data_ev16/'+'neurons'+str(neuron)+'_LR'+str(lr)+'_Gamma'+str(gamma)+'_BS'+str(bs)+'_totSteps'+str(tSteps)+'_assimStep50_obsNosie1.0_maxgradnorm'+str(max_grad_norms)+'_vfcoeff'+str(vf)+'/sol2', sol2=sol2)
np.savez('data_ev16/'+'neurons'+str(neuron)+'_LR'+str(lr)+'_Gamma'+str(gamma)+'_BS'+str(bs)+'_totSteps'+str(tSteps)+'_assimStep50_obsNosie1.0_maxgradnorm'+str(max_grad_norms)+'_vfcoeff'+str(vf)+'/solR', solR=solR)

np.savez('data_ev16/'+'neurons'+str(neuron)+'_LR'+str(lr)+'_Gamma'+str(gamma)+'_BS'+str(bs)+'_totSteps'+str(tSteps)+'_assimStep50_obsNosie1.0_maxgradnorm'+str(max_grad_norms)+'_vfcoeff'+str(vf)+'/pred', x=x)
np.savez('data_ev16/'+'neurons'+str(neuron)+'_LR'+str(lr)+'_Gamma'+str(gamma)+'_BS'+str(bs)+'_totSteps'+str(tSteps)+'_assimStep50_obsNosie1.0_maxgradnorm'+str(max_grad_norms)+'_vfcoeff'+str(vf)+'/ref',  xR=xR)


/data1/RL/test_recallWhatIdid/PerfectModels_testNoise/Full_MDP_allobserved/stable-baselines3/stable_baselines3/common/save_util.py:278: UserWarning: Path 'data_ev16/neurons128_LR0.001_Gamma0.1_BS100_totSteps5000000_assimStep50_obsNosie1.0_maxgradnorm0.8_vfcoeff0.9' does not exist. Will create it.
  warnings.warn(f"Path '{path.parent}' does not exist. Will create it.")
